### ISSUE TITLE
kdenlive project hangs on import, melt player stuck after 4 seconds

### ISSUE THREAD

**Issue by languitar** [mltframework/mlt#252]
I have a kdenlive project which I could edit without problems so far. However, trying to reopen the project makes kdenlive freeze. This tracks down to mlt itself. If I open the project with `melt`, the player gets stuck after 4 seconds. `gdb` shows the following threads:

```
(gdb) bt
#0  0x00007f3bc2410fd3 in select () at /usr/lib/libc.so.6
#1  0x0000555555558689 in  ()
#2  0x0000555555556e55 in  ()
#3  0x00007f3bc234b4ca in __libc_start_main () at /usr/lib/libc.so.6
#4  0x000055555555749a in  ()
(gdb) thread apply all bt

Thread 8 (Thread 0x7f3b58df8700 (LWP 24550)):
#0  0x00007f3bc29fa1ad in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f3ba6ce6512 in  () at /usr/lib/mlt/libmltsdl.so
#2  0x00007f3bc29f4049 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f3bc2418f0f in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f3bc301c700 (LWP 24549)):
#0  0x00007f3bc240ef76 in ppoll () at /usr/lib/libc.so.6
#1  0x00007f3bb7ca579d in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#2  0x00007f3bb7ca5d8e in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#3  0x00007f3bc278797f in  () at /usr/lib/libSDL2-2.0.so.0
#4  0x00007f3bc26eaf70 in  () at /usr/lib/libSDL2-2.0.so.0
#5  0x00007f3bc274cc9f in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007f3bc279e78a in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007f3bc29f4049 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f3bc2418f0f in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f3b92153700 (LWP 24548)):
#0  0x00007f3bc29fa1ad in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f3bc2c29d74 in  () at /usr/lib/libmlt.so.6
#2  0x00007f3bc29f4049 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f3bc2418f0f in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f3b92954700 (LWP 24547)):
#0  0x00007f3bc29fa1ad in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f3ba6ce7284 in  () at /usr/lib/mlt/libmltsdl.so
#2  0x00007f3bc29f4049 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f3bc2418f0f in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f3b92995700 (LWP 24546)):
#0  0x00007f3bc240ef76 in ppoll () at /usr/lib/libc.so.6
#1  0x00007f3bb7ca579d in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#2  0x00007f3bb7ca5d8e in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#3  0x00007f3bb7ca5e40 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#4  0x00007f3bc2787b00 in  () at /usr/lib/libSDL2-2.0.so.0
#5  0x00007f3bc274cc9f in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007f3bc279e78a in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007f3bc29f4049 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f3bc2418f0f in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f3b938b7700 (LWP 24545)):
#0  0x00007f3bc240ee9d in poll () at /usr/lib/libc.so.6
#1  0x00007f3bb280fc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f3bb280fd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f3ba8f2f061 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#4  0x00007f3ba8ed2ffb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007f3ba8cec40e in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f3b9e82a396 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007f3ba8cf115b in  () at /usr/lib/libQt5Core.so.5
#8  0x00007f3bc29f4049 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f3bc2418f0f in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f3b9cd5b700 (LWP 24544)):
#0  0x00007f3bc240ee9d in poll () at /usr/lib/libc.so.6
#1  0x00007f3bb8c2c8e0 in  () at /usr/lib/libxcb.so.1
#2  0x00007f3bb8c2e679 in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007f3b9ecd972a in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007f3ba8cf115b in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f3bc29f4049 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f3bc2418f0f in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f3bc2ffa700 (LWP 24540)):
#0  0x00007f3bc2410fd3 in select () at /usr/lib/libc.so.6
#1  0x0000555555558689 in  ()
#2  0x0000555555556e55 in  ()
#3  0x00007f3bc234b4ca in __libc_start_main () at /usr/lib/libc.so.6
#4  0x000055555555749a in  ()
```

I have compiled the git version of today and the same issue appears.

**Comment by languitar** [comment]
Weird, gone after a reboot. Probably a kernel / filesystem issue then...
