### ISSUE TITLE
Missed init_mlt function for python binding

### ISSUE THREAD

**Issue by AS383** [mltframework/mlt#501]
Using melt 6.18.0 and Python 2.7.15 I get ImportError: dynamic module does not define init function (init_mlt):

```
Python 2.7.15 (default, Oct  9 2019, 22:57:09) 
[GCC 5.5.0 20171010 (ROSA)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mlt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/mlt.py", line 21, in <module>
    _mlt = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/mlt.py", line 20, in swig_import_helper
    return importlib.import_module('_mlt')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dynamic module does not define init function (init_mlt)
```

**Comment by ddennedy** [comment]
Python 2 is no longer supported, and this looks to be related to swig as that is not a MLT function.

**Comment by AS383** [comment]
Thanks! I fix my spec file (copy mlt.py and _mlt.so to python3.5/site-packages) and now importing work.
