### ISSUE TITLE
Wipe transition segfaults

### ISSUE THREAD

**Issue by Pistos** [mltframework/mlt#535]
I am trying to debug an issue in kdenlive (https://invent.kde.org/kde/kdenlive/issues/575).  I am using mlt @ 5e906b13cab7f28bbef43a33c20dbe24c2ca1f8d .  When I run with gdb, I get:

```
Thread 38 "RenderThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb9687700 (LWP 17400)]
0x00007fffdb881e8a in scale_luma (invert=0, src_height=1080, src_width=1920, src_buf=0x0, dest_height=1080, dest_width=1920, dest_buf=0x7fffb369a812)
    at transition_composite.c:547
```

and that line is in https://github.com/mltframework/mlt/blob/5e906b13cab7f28bbef43a33c20dbe24c2ca1f8d/src/modules/core/transition_composite.c#L532-L552

Any ideas why this is segfaulting?

**Comment by max-verem** [comment]
it segfaulting because src_buf=0x0

provide deeper backtrace

could you export project to mlt xml format and try it?

**Comment by Pistos** [comment]
Here's the `bt`:

```
#0  0x00007fffdb881e8a in scale_luma (invert=0, src_height=1080, src_width=1920, src_buf=0x0, dest_height=1080, dest_width=1920, dest_buf=0x7fffb369a812)
    at transition_composite.c:547
#1  get_luma (height=1080, width=1920, properties=0x60c0018052c0, self=0x60c0018052c0) at transition_composite.c:707
#2  transition_get_image
    (a_frame=a_frame@entry=0x608000570e20, image=image@entry=0x7fffb96869e8, format=format@entry=0x6140006ed04c, width=width@entry=0x7fffb9686c84, height=height@entry=0x7
fffb9686c88, writable=writable@entry=1) at transition_composite.c:1219
#3  0x00007ffff6fd71bf in mlt_frame_get_image
    (self=0x608000570e20, buffer=0x7fffb96869e8, format=0x6140006ed04c, width=0x7fffb9686c84, height=0x7fffb9686c88, writable=1) at mlt_frame.c:620
#4  0x00007ffff6fd71bf in mlt_frame_get_image
    (self=self@entry=0x608000570e20, buffer=buffer@entry=0x7fffb96869e8, format=format@entry=0x6140006ed04c, width=width@entry=0x7fffb9686c84, height=height@entry=0x7fffb
9686c88, writable=writable@entry=1) at mlt_frame.c:620
#5  0x00007fffdfd1450a in get_image(mlt_frame, uint8_t**, mlt_image_format*, int*, int*, int)
    (a_frame=a_frame@entry=0x608000570ca0, image=image@entry=0x7fffb9686c98, format=format@entry=0x6140006ed04c, width=width@entry=0x7fffb9686c84, height=height@entry=0x7
fffb9686c88, writable=writable@entry=0) at transition_qtblend.cpp:189
#6  0x00007ffff6fd71bf in mlt_frame_get_image
    (self=self@entry=0x608000570ca0, buffer=buffer@entry=0x7fffb9686c98, format=format@entry=0x6140006ed04c, width=width@entry=0x7fffb9686c84, height=height@entry=0x7fffb
9686c88, writable=writable@entry=0) at mlt_frame.c:620
#7  0x00007ffff6feda5c in producer_get_image
    (self=self@entry=0x608000570c20, buffer=buffer@entry=0x7fffb9686c98, format=format@entry=0x6140006ed04c, width=width@entry=0x7fffb9686c84, height=height@entry=0x7fffb
9686c88, writable=writable@entry=0) at mlt_tractor.c:371
#8  0x00007ffff6fd71bf in mlt_frame_get_image
    (self=self@entry=0x608000570c20, buffer=buffer@entry=0x7fffb9686c98, format=format@entry=0x6140006ed04c, width=width@entry=0x7fffb9686c84, height=height@entry=0x7fffb
9686c88, writable=writable@entry=0) at mlt_frame.c:620
#9  0x00007ffff6feaea7 in consumer_read_ahead_thread (arg=<optimized out>) at mlt_consumer.c:907
#10 0x00000000015a4467 in RenderThread::run() (this=0x6040008d2bd0) at /misc/git/kdenlive/src/monitor/glwidget.cpp:1430
#11 0x00007ffff23e0032 in  () at /usr/lib64/libQt5Core.so.5
#12 0x00007ffff1f36408 in start_thread () at /lib64/libpthread.so.0
#13 0x00007ffff1e3e8df in clone () at /lib64/libc.so.6
```

The line of code in kdenlive is [this](https://invent.kde.org/kde/kdenlive/-/blob/bf3ec045f3f1560b6a4695c2a98e0fdc5ddd3cb8/src/monitor/glwidget.cpp#L1430).

**Comment by ddennedy** [comment]
I found the logic in the code allows the code to reach this code point and use a null buffer pointer when a PGM luma file fails to load for some reason. I simply added a pointer check to prevent trying to scale the image buffer when null. I could not test within Kdenlive as I am not setup for that, but it was an easy logic problem to find and patch. Hopefully, you can get some build in the near future with this change to test it yourself.

**Comment by Pistos** [comment]
Thank you.  I tried with mlt @ 48a2262 , and it fixes the issue!
