### ISSUE TITLE
Crash with pixelize effect

### ISSUE THREAD

**Issue by frdbr** [mltframework/mlt#689]
A crash is happening when using the pixeliz0r effect reported [here](https://bugs.kde.org/show_bug.cgi?id=428794).

[Full log](https://github.com/mltframework/mlt/files/6204574/bt.txt)

```
Thread 76 (Thread 0x7ffe9a7fc640 (LWP 19667) "RenderThread"):
#0  0x00007fffa9a6b3e3 in f0r_update () at /usr/lib64/frei0r-1/pixeliz0r.so
#1  0x00007fffc77a8282 in f0r_update_slice (id=<optimized out>, index=<optimized out>, count=<optimized out>, context=<optimized out>) at frei0r_helper.c:63
        ctx = <optimized out>
        slice_height = <optimized out>
        slice_offset = <optimized out>
        input = <optimized out>
        output = <optimized out>
#2  0x00007ffff6afc9a8 in mlt_slices_worker (p=0x7fff84306fb0) at mlt_slices.c:117
        id = 5
        idx = 0
        r = 0x7fff51d70f40
        ctx = 0x7fff84306fb0
        __FUNCTION__ = "mlt_slices_worker"
#3  0x00007ffff4400299 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff4bcb053 in clone () at /usr/lib/libc.so.6
```

**Comment by ddennedy** [comment]
Please do not report bugs found in another project -Frei0r - while using kdenlive to here.

**Comment by frdbr** [comment]
Will report in frei0r thanks.
