### ISSUE TITLE
crash during audio processing

### ISSUE THREAD

**Issue by cy6erGn0m** [mltframework/mlt#80]
mlt 0.9.6 crashes at memcpy. See the stacktrace (I believe it is meaningful and line numbers are correct):

```
Thread 11 (Thread 0x7f0d3208d700 (LWP 4775)):
[KCrash Handler]
#5  0x00007f0d62c32026 in __memcpy_sse2_unaligned () at /lib64/libc.so.6
#6  0x00007f0d4fd2471d in producer_get_audio (__len=4, __src=<optimized out>, __dest=<optimized out>) at /usr/include/bits/string3.h:51
#7  0x00007f0d4fd2471d in producer_get_audio (bytes_per_sample=4, channels=2, samples=4608, src=0x7f0d2811eca0, dest=<optimized out>) at producer_avformat.c:1999
#8  0x00007f0d4fd2471d in producer_get_audio (fps=24, timecode=<optimized out>, samples=2000, pkt=..., ignore=0x7f0d3208ca84, self=0x50ece60) at producer_avformat.c:2095
#9  0x00007f0d4fd2471d in producer_get_audio (frame=frame@entry=0x7f0d28000af0, buffer=buffer@entry=0x7f0d3208ce00, format=format@entry=0x3271620, frequency=frequency@entry=0x7f0d3208cdf8, channels=channels@entry=0x7f0d3208cbcc, samples=samples@entry=0x7f0d3208cdfc) at producer_avformat.c:2306
#10 0x00007f0d64775be9 in mlt_frame_get_audio (self=self@entry=0x7f0d28000af0, buffer=buffer@entry=0x7f0d3208ce00, format=format@entry=0x3271620, frequency=frequency@entry=0x7f0d3208cdf8, channels=channels@entry=0x7f0d3208cbcc, samples=samples@entry=0x7f0d3208cdfc) at mlt_frame.c:749
#11 0x00007f0d4576bab1 in filter_get_audio (frame=frame@entry=0x7f0d28000af0, buffer=buffer@entry=0x7f0d3208ce00, format=format@entry=0x3271620, frequency=frequency@entry=0x7f0d3208cdf8, channels=channels@entry=0x7f0d3208cdf4, samples=samples@entry=0x7f0d3208cdfc) at filter_audiochannels.c:32
#12 0x00007f0d64775be9 in mlt_frame_get_audio (self=self@entry=0x7f0d28000af0, buffer=buffer@entry=0x7f0d3208ce00, format=format@entry=0x3271620, frequency=frequency@entry=0x7f0d3208cdf8, channels=channels@entry=0x7f0d3208cdf4, samples=samples@entry=0x7f0d3208cdfc) at mlt_frame.c:749
#13 0x00007f0d45efb28f in resample_get_audio (frame=frame@entry=0x7f0d28000af0, buffer=buffer@entry=0x7f0d3208ce00, format=format@entry=0x3271620, frequency=frequency@entry=0x7f0d3208cdf8, channels=channels@entry=0x7f0d3208cdf4, samples=samples@entry=0x7f0d3208cdfc) at filter_resample.c:53
#14 0x00007f0d64775be9 in mlt_frame_get_audio (self=self@entry=0x7f0d28000af0, buffer=buffer@entry=0x7f0d3208ce00, format=format@entry=0x3271620, frequency=frequency@entry=0x7f0d3208cdf8, channels=channels@entry=0x7f0d3208cdf4, samples=samples@entry=0x7f0d3208cdfc) at mlt_frame.c:749
#15 0x00007f0d6478852a in consumer_read_ahead_thread (arg=0x3c58520) at mlt_consumer.c:815
#16 0x00007f0d649a20a4 in start_thread () at /lib64/libpthread.so.0
#17 0x00007f0d62c8708d in clone () at /lib64/libc.so.6
```

**Comment by ddennedy** [comment]
There was a fix after the 0.9.6 release that fixes this when the audio stream has more than 8 channels. How many channels are in the file? (Note that the "channels=2" in the backtrace is the output number of channels, not the input.)

**Comment by cy6erGn0m** [comment]
@ddennedy ffprobe told me the following:

```
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
```

**Comment by ddennedy** [comment]
How reproducible is this crash? Does it crash consistently on just this fie, consistently if you do X Y and Z, or was this a random crash?

**Comment by cy6erGn0m** [comment]
@ddennedy I can crash it any times. The video file is too big to attach it somewhere. I can attach core dump if you want.

**Comment by ddennedy** [comment]
No core dump. How can I reproduce it? If you think it is this file in particular, send the full ffprobe output, and I will test with a similar file I have.

**Comment by cy6erGn0m** [comment]
```
ffprobe version 2.7.1 Copyright (c) 2007-2015 the FFmpeg developers
  built with gcc 4.8 (SUSE Linux)
  configuration: --shlibdir=/usr/lib64 --prefix=/usr --mandir=/usr/share/man --libdir=/usr/lib64 --enable-shared --disable-static --enable-debug --disable-stripping --extra-cflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --enable-pic --optflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --enable-gpl --enable-x11grab --enable-version3 --enable-pthreads --datadir=/usr/share/ffmpeg --enable-avfilter --enable-libpulse --enable-libwebp --enable-libvpx --enable-libopus --enable-libmp3lame --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libxvid --enable-libx264 --enable-libx265 --enable-libschroedinger --enable-libgsm --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-postproc --enable-libdc1394 --enable-librtmp --enable-libfreetype --enable-avresample --enable-libtwolame --enable-libvo-aacenc --enable-gnutls --enable-libass --enable-frei0r --enable-libcelt --enable-libcdio --enable-ladspa
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from 'swr.mkv':
  Metadata:
    encoder         : libebml v1.3.0 + libmatroska v1.4.1
    creation_time   : 2015-06-24 06:11:22
  Duration: 00:43:48.20, start: 0.000000, bitrate: 3133 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p, 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Stream #0:2(rus): Subtitle: subrip (default)
    Metadata:
      title           : Русские, notabenoid Stap_dono
    Stream #0:3(eng): Subtitle: subrip
    Metadata:
      title           : Английские
```

**Comment by cy6erGn0m** [comment]
I have compiled everything from scratch (ffmpeg, movit and mlt) to a temporary prefix and got it work. No crash with master versions.

**Comment by ddennedy** [comment]
Thank you. If you test with Shotcut, which uses MLT git master but with FFmpeg 2.3, then it will help to determine if something was fixed in FFmpeg or MLT. Shotcut is a convenient binary download.
